### ISSUE TITLE
请问您,使用上是否有版权限制? 您采取何种版权?

### ISSUE THREAD

**Issue by torukskywalker** [WF-2021/BTC_FPGA_MINER#1]

**Comment by WF-2021** [comment]
感谢您有很强的版权意识！我们最近正在讨论和选择一款适合的开源协议。确定开源协议之后，会回复您。我们目前的FPGA工程是在vivado2019.2上，并基于Xilinx的XC7A100T，可实现100MHash/s的算力。以上参数可供您参考，谢谢。

**Comment by WF-2021** [comment]
您好，我们的工程最终选择了BSD开源协议。您仅需遵守该协议，即可用于二次开发。
